export default [
  'Istu alas',
  'Nouse ylös',
  'Käänny vasemmalle',
  'Käänny oikealle',
  'Avaa uusi juoma',
  'Juo vettä',
  'Ota huikka',
  'Seuraa huikkaa TikTokissa 🤮',
  'Poista tämä juomapeli',
  '8 punnerrusta',
  'Älä tee aviorikosta',
  'Mee kotiin, heikko 🤓',
  'Juokse talon ympäri',
  'Opettele jongleeraamaan',
  'Kävele käsillä',
  'Pyydä kirjastonhoitajaa suosittelemaan sinulle lukemista. Kerro, mitä luet yleensä ja pyydä nyt jotain ihan muuta. Ehkä löydät uuden suosikkikirjailijan!',
  'Kerro vitsi',
  'käy lähipuistossa pelottelemassa lapsia',
  'Tanssi ripaskaa',
  'Tee 5 vatsalihasliikettä',
];
